// <auto-generated />
using System;
using MBA.Educacao.Online.Pagamentos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MBA.Educacao.Online.API.Migrations.Pagamento
{
    [DbContext(typeof(PagamentoContext))]
    partial class PagamentoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("MBA.Educacao.Online.Pagamentos.Domain.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataConfirmacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("DataPagamento");

                    b.HasIndex("MatriculaId");

                    b.ToTable("Pagamentos", (string)null);
                });

            modelBuilder.Entity("MBA.Educacao.Online.Pagamentos.Domain.Pagamento", b =>
                {
                    b.OwnsOne("MBA.Educacao.Online.Pagamentos.Domain.DadosCartao", "DadosCartao", b1 =>
                        {
                            b1.Property<Guid>("PagamentoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CVV")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("TEXT")
                                .HasColumnName("CVV");

                            b1.Property<string>("NomeTitular")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("NomeTitular");

                            b1.Property<string>("NumeroCartao")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("NumeroCartao");

                            b1.Property<string>("Validade")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("TEXT")
                                .HasColumnName("Validade");

                            b1.HasKey("PagamentoId");

                            b1.ToTable("Pagamentos");

                            b1.WithOwner()
                                .HasForeignKey("PagamentoId");
                        });

                    b.OwnsOne("MBA.Educacao.Online.Pagamentos.Domain.StatusPagamento", "StatusPagamento", b1 =>
                        {
                            b1.Property<Guid>("PagamentoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("MotivoRejeicao")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("MotivoRejeicao");

                            b1.Property<int>("Status")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Status");

                            b1.HasKey("PagamentoId");

                            b1.ToTable("Pagamentos");

                            b1.WithOwner()
                                .HasForeignKey("PagamentoId");
                        });

                    b.Navigation("DadosCartao")
                        .IsRequired();

                    b.Navigation("StatusPagamento")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
